application: starter
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# dev mod urls
#- url: /bower_components
#  static_dir: static/bower_components/
#
#- url: /app/(.*\.html)$
#  mime_type: text/html
#  static_files: static/src/app/\1
#  upload: static/src/app/(.*\.html)$
#
#- url: /assets/images/(.*\.(gif|png|jpg))
#  static_files: static/src/assets/images/\1
#  upload: static/src/assets/images/(.*\.(gif|png|jpg))
#
#- url: /app/(.+)
#  static_files: static/.tmp/serve/app/\1
#  upload: static/.tmp/serve/app/(.*)
#
#- url: /index.html
#  static_files: static/.tmp/serve/index.html
#  upload: static/.tmp/serve/index.html
#
#- url: /
#  static_files: static/.tmp/serve/index.html
#  upload: static/.tmp/serve/index.html

# prod
- url: /(.+)
  static_files: static/dist/\1
  upload: static/dist/(.*)

- url: /
  static_files: static/dist/index.html
  upload: static/dist/index.html

libraries:
- name: webapp2
  version: "2.5.2"

skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?
